### ISSUE TITLE
Problems when running on MacOS

### ISSUE THREAD

**Issue by nriesco** [Bellspringsteen/OurCamera#7]
I have a couple of issues when running on OSX.

1. I cannot run "generate_tfrecord" like this `./generate_tfrecord` I must first change it `chmod +x` and then run it like this `./generate_tfrecord.py` (including `=.py` at the end).
2. When running the command I get a strange error, both activating and not activating my tensorflow environment (`source ./bin/activate`)

```
./generate_tfrecord.py --folder=data/ --train_ratio=.70

(tensorflow3) NicoPro:OurCamera nriesco$ ./generate_tfrecord.py --folder=data/ --train_ratio=.70
./generate_tfrecord.py: line 14: Processing Image and Annotation Dataset

This executable is used to convert the image and label dataset to test and train TF Records:

A folder should be specified which contains folders labeled images/ and labels/
Each jpg image file should contain a corresponding label file with the same name but with .xml extension
A ratio of test to training should be specified i.e. .70

Example usage:
    ./generate_tfrecord         --folder=path/to/data_dir         --train_ratio=.70

: No such file or directory
from: can't read /var/mail/__future__
from: can't read /var/mail/PIL
./generate_tfrecord.py: line 20: import: command not found
./generate_tfrecord.py: line 21: import: command not found
from: can't read /var/mail/argparse
./generate_tfrecord.py: line 23: import: command not found
./generate_tfrecord.py: line 24: import: command not found
./generate_tfrecord.py: line 25: import: command not found
./generate_tfrecord.py: line 26: import: command not found
./generate_tfrecord.py: line 27: import: command not found
./generate_tfrecord.py: line 28: syntax error near unexpected token `'./models-master/research/''
./generate_tfrecord.py: line 28: `sys.path.append('./models-master/research/')'

```

It does not matter if I change the path to an absoulte one, add a trailing slash, etc.

**Comment by aaronbauman** [comment]
I had to do this:
```
ln -s models models-master
python generate_tfrecord.py -folder="data/" -train_ratio=.70
```

**Comment by nriesco** [comment]
Thanks!

Now it does seem to run but I get another error, like another issue [https://github.com/Bellspringsteen/OurCamera/issues/6](https://github.com/Bellspringsteen/OurCamera/issues/6)

```
(tensorflow3) NicoPro:OurCamera nriesco$ python generate_tfrecord.py -folder="data/" -train_ratio=.70
Running on data/ with ratio 0.7
Traceback (most recent call last):
  File "generate_tfrecord.py", line 132, in <module>
    tf.app.run()
  File "/Users/nriesco/tensorflow3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "generate_tfrecord.py", line 124, in main
    tf_example = create_tf_example_from_jpg_xml(images_path+filename+'.jpg', labels_path+filename+'.xml')
  File "generate_tfrecord.py", line 82, in create_tf_example_from_jpg_xml
    'image/filename': dataset_util.bytes_feature(jpg_file),
  File "./models-master/research/object_detection/utils/dataset_util.py", line 30, in bytes_feature
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
TypeError: 'data/images/2017-12-27 00:19:55.544815.jpg' has type str, but expected one of: bytes
(tensorflow3) NicoPro:OurCamera nriesco$
```

**Comment by nriesco** [comment]
@aaronbauman I had issues with files containing spaces in OSX before when running via scripts and I removed every image but one and rename it to `1.jpg` (same with label) and no error was thrown.

So is related to filenames containing spaces, at least on OSX

**Comment by aaronbauman** [comment]
hmm, i am on OSX 10.12 and didn't have that issue with filenames.
what version of OSX and python are you running?
I'm finally up and running

**Comment by Bellspringsteen** [comment]
I have tried on 10.13 and 10.12 and I dont get these issues with filenames. What versions are you running?
